In [1]:
import numpy as np

In [5]:
marks=np.array([78,65,89,56,92])
print("Array:", marks)


Array: [78 65 89 56 92]


In [6]:
print("Number of dimensions:", marks.ndim)
print("Shape:", marks.shape)
print("Size:", marks.size)
print("Data type:", marks.dtype)
print("Item size:", marks.itemsize)

Number of dimensions: 1
Shape: (5,)
Size: 5
Data type: int32
Item size: 4


In [16]:
#Question 2 – Student Marks Access
mar=np.array([72,85,64,90,76])

In [14]:
mar[:4]


array([72, 85, 64, 90])

In [15]:
mar[:5:2]

array([72, 64, 76])

In [19]:
#Question 3 – Subject-wise Marks
m=np.array([78, 85, 90, 65, 72, 80, 88, 91, 84, 56, 62, 70, 95, 89, 92])
reshape=m.reshape(5,3)
print(reshape)

[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]


In [23]:
#Question 4 – Internal and External Marks
internal = np.array([20, 18, 22, 19, 21])
external = np.array([70, 65, 68, 72, 75])
total=internal+external
print("final mark",total)

final mark [90 83 90 91 96]


In [29]:
#Question 5 – Pass Percentage Analysis
mark=np.array([45, 78, 56, 32, 91])
pass_mark=mark>=50
print(pass_mark)
print(mark[pass_mark])

[False  True  True False  True]
[78 56 91]


In [31]:
#Question 6 – Average Marks
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])
avg=np.mean(marks,axis=1)
print("Average",avg)

Average [84.33333333 72.33333333 87.66666667 62.66666667 92.        ]


In [36]:
#Question 7 – Class Performance Statistics
mark=np.array( [67, 82, 91, 74, 58])
total=np.sum(mark)
average=np.mean(mark)
low=np.min(mark)
high=np.max(mark)
stand=np.std(mark)
print("Total: ",total)
print("average: ",average)
print("low: ",low)
print("high: ",high)
print("StandDeviation",stand)

Total:  372
average:  74.4
low:  58
high:  91
StandDeviation 11.46472851837321


In [42]:
#Question 9 – Student-wise Performance
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])
total=np.sum(marks,axis=1)
print("total",total)

total [253 217 263 188 276]


In [44]:
#Question 10 – Student Ranking

marks = np.array([245, 278, 219, 290, 256])
sorted_marks = np.sort(marks)

ranking = sorted_marks[::-1]

print("Marks in ranking order:", ranking)

Marks in ranking order: [290 278 256 245 219]


In [45]:
#Question 11 – Duplicate Marks Analysis
marks = np.array([85, 92, 85, 76, 92])

unique_marks = np.unique(marks)

print("Unique marks:", unique_marks)

Unique marks: [76 85 92]


In [46]:
#Question 12 – Missing Marks
import numpy as np
marks = np.array([78, 85, np.nan, 92, 67])
average = np.nanmean(marks)
print("Average marks:", average)

Average marks: 80.5


In [47]:
#Question 13 – Grade Classification
marks = np.array([95, 82, 74, 61, 45])

grades = np.where(marks >= 90, "A",
         np.where(marks >= 80, "B",
         np.where(marks >= 70, "C",
         np.where(marks >= 60, "D", "F"))))

print("Marks:", marks)
print("Grades:", grades)

Marks: [95 82 74 61 45]
Grades: ['A' 'B' 'C' 'D' 'F']


In [49]:
#Question 14 – Random Marks Generation

marks = np.random.randint(0, 101, 5)

print("Generated Marks:", marks)

# Basic statistical analysis
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard Deviation:", np.std(marks))

Generated Marks: [10 64 21 94 60]
Total: 249
Average: 49.8
Highest: 94
Lowest: 10
Standard Deviation: 30.570574086856794


In [50]:
#Question 15 – Student Performance Analysis
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

total = np.sum(marks, axis=1)

average = np.mean(marks, axis=1)

highest = np.max(marks, axis=1)

lowest = np.min(marks, axis=1)

class_average = np.mean(marks)

above_average = np.where(average > class_average)[0] + 1

print("Total marks:", total)
print("Average marks:", average)
print("Highest marks:", highest)
print("Lowest marks:", lowest)
print("Class average:", class_average)
print("Students above class average:", above_average)

Total marks: [253 217 263 188 276]
Average marks: [84.33333333 72.33333333 87.66666667 62.66666667 92.        ]
Highest marks: [90 80 91 70 95]
Lowest marks: [78 65 84 56 89]
Class average: 79.8
Students above class average: [1 3 5]
